<a href="https://colab.research.google.com/github/jasonhckim/NumPy/blob/main/NumPy_Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
# Reading the dataset
import numpy as np

data_file='/makeSenseOfCensus.csv'

In [56]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [57]:
#printing the type of data

print("\nType fo data: \n\n", type(data))


Type fo data: 

 <class 'numpy.ndarray'>


In [58]:
# append new record to data using np.concatenate

new_record = [[50,9,4,1,0,0,40,0]]

In [59]:
np.concatenate([new_record,data], axis = 0)

array([[50.,  9.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [60]:
print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [61]:
# age of people in index 0
age = data[:,0]
print(age)

[39. 50. 38. 53. 28. 37. 49. 52. 31. 42. 37. 30. 23. 32. 40. 34. 25. 32.
 38. 43. 40. 54. 35. 43. 59. 56. 19. 54. 39. 49. 23. 20. 45. 30. 22. 48.
 21. 19. 31. 48. 31. 53. 24. 49. 25. 57. 53. 44. 41. 29. 25. 18. 47. 50.
 47. 43. 46. 35. 41. 30. 30. 32. 48. 42. 29. 36. 28. 53. 49. 25. 19. 31.
 29. 23. 79. 27. 40. 67. 18. 31. 18. 52. 46. 59. 44. 53. 49. 33. 30. 43.
 57. 37. 28. 30. 34. 29. 48. 37. 48. 32. 76. 44. 47. 20. 29. 32. 17. 30.
 31. 42. 24. 38. 56. 28. 36. 53. 56. 49. 55. 22. 21. 40. 30. 29. 19. 47.
 20. 31. 35. 39. 28. 24. 38. 37. 46. 38. 43. 27. 20. 49. 61. 27. 19. 45.
 70. 31. 22. 36. 64. 43. 47. 34. 33. 21. 52. 48. 23. 71. 29. 42. 68. 25.
 44. 28. 45. 36. 39. 46. 18. 66. 27. 28. 51. 27. 28. 27. 21. 34. 18. 33.
 44. 43. 30. 40. 37. 34. 41. 53. 31. 58. 38. 24. 41. 47. 41. 23. 36. 40.
 35. 24. 26. 19. 51. 42. 37. 18. 36. 35. 58. 17. 44. 37. 35. 60. 54. 37.
 50. 38. 45. 25. 31. 64. 90. 54. 53. 18. 60. 66. 75. 65. 35. 41. 25. 33.
 28. 59. 40. 41. 38. 23. 40. 41. 24. 20. 38. 56. 58

In [62]:
# find max age 
max_age = age.max()
print(max_age)

90.0


In [63]:
#find min age
min_age = age.min()
print(min_age)

17.0


In [64]:
#find mean age
age_mean = age.mean()
print(age_mean)

38.051


In [65]:
#find standard deviation
age_std = age.std()
print(age_std)

13.342803266180612


In [66]:
#number of citizen per race
race_0 = data[data[:,2]==0]
print(race_0)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]


In [67]:
race_1 = data[data[:,2]==1]
race_2 = data[data[:,2]==2]
race_3 = data[data[:,2]==3]
race_4 = data[data[:,2]==4]
print(race_1)
print(race_2)
print(race_3)
print(race_4)

[[3.000e+01 1.300e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [4.000e+01 1.100e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [5.400e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 6.000e+01
  1.000e+00]
 [3.000e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 1.573e+03 3.500e+01
  0.000e+00]
 [4.900e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.300e+01 1.300e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.400e+01 1.400e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [6.000e+01 9.000e+00 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.200e+01 9.000e+00 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.700e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 7.500e+01
  1.000e+00]
 [3.900e+01 1.400e+01 1.000e+00 0.000e+00 3.464e+03 0.000e+00 4.0

In [104]:
#len per race
len_0 = len(race_0)
print('Length of race_0',len_0)
len_1 = len(race_1)
print('Length of race_1',len_1)
len_2 = len(race_2)
print('Length of race_2',len_2)
len_3 = len(race_3)
print('Length of race_3',len_3)
len_4 = len(race_4)
print('Length of race_4',len_4)

Length of race_0 10
Length of race_1 27
Length of race_2 110
Length of race_3 6
Length of race_4 847


In [69]:
#find the minimum number of citizen in a race
min_cit = min(len_0,len_1,len_2,len_3,len_4)

In [70]:
if min_cit == len_0:
  print('Race_0 has Minimum no. of Citezen of {}.'.format(len_0)) 
elif min_cit == len_1:
  print('Race_1 has Minimum no. of Citezen of {}.'.format(len_1))
elif min_cit == len_2:
  print('Race_2 has Minimum no. of Citezen of {}.'.format(len_2))
elif min_cit == len_3:
  print('Race_3 has Minimum no. of Citezen of {}.'.format(len_3))  
elif min_cit == len_4:
  print('Race_4 has Minimum no. of Citezen of {}.'.format(len_4)) 
else:
  pass


Race_3 has Minimum no. of Citezen of 6.


In [71]:
minority_race = len(race_3)
print('Minority race is race_3 with:',minority_race)

Minority race is race_3 with: 6


In [90]:
#find the number of citizen over age 60
senior_citizen = data[age>60]

In [88]:
#find the working hour sum of citizen over age 60
working_hour_sum =sum(senior_citizen[:,6])
print(working_hour_sum)

1917.0


In [93]:
#find len of senior citizen
senior_citizen_len = len(senior_citizen)

In [94]:
#find the average working hour of senior citizen
avg_working_hours = working_hour_sum/senior_citizen_len
print(avg_working_hours)

31.42622950819672


In [95]:
#find the high and low salary
high = data[data[:,1]>10]
low = data[data[:,1]<10]

In [97]:
# find the len of high and low salary
print(high)
print(low)
print(len(high))
print(len(low))

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
[[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [47.  9.  4. ...  0. 50.  1.]
 [35.  9.  4. ...  0. 45.  0.]
 [56.  9.  4. ...  0. 55.  1.]]
327
448


In [101]:
#find the average pay of high
avg_pay_high = (high[:,7])
print(avg_pay_high.mean())

0.42813455657492355


In [103]:
#find the average pay of low
avg_pay_low = (low[:,7])
print(avg_pay_low.mean())

0.12723214285714285
